adding the required feature in the script as last_del
imambungo/dirjump pull request #2
Opened 2019-10-10 16:29 UTC by AutomationBoi

fixing issue number #1
kindly test the code and let me know the changes required
it will help if you can attach some error screenshots
Regards

2019-10-10 23:44 UTC, imambungo requested changes

2019-10-10 23:44 UTC, imambungo commented on dirjump
>  # Source: https://stackoverflow.com/a/27056916/9157799
These comments should be placed above `get_nth_path()` function.

2019-10-10 23:44 UTC, imambungo commented on dirjump
> +	if [[ -f "$last_del" ]]
Should be `$last_dir_remove`.

2019-10-10 23:44 UTC, imambungo commented on dirjump
> +        fi
These 4 lines should be placed below `print_directory_history` (line 108) to make it works.

And a little indentation fix:
```suggestion
      fi
```

2019-10-10 23:44 UTC, imambungo commented on dirjump
> +        delta_hour=`echo "($curr_time-$time_del)/3600|bc"`
```suggestion
        delta_hour=`echo "($curr_time-$time_del)/3600" | bc`
```

2019-10-10 23:44 UTC, imambungo commented on dirjump
> +        echo "A path was last removed $delta_hour hours ago."
Add indentation to improve readability.
```suggestion
                echo "A path was last removed $delta_hour hours ago."
```

2019-10-10 23:44 UTC, imambungo commented on dirjump
> +        echo "A path was last removed $delta_hour seconds ago."
```suggestion
                echo "A path was last removed $delta_hour seconds ago."
```

2019-10-11 00:27 UTC, imambungo requested changes

2019-10-11 00:27 UTC, imambungo commented on dirjump
> +	date +%s > "$last_dir_remove"
This line should be moved to somewhere else. The function `delete_a_dir_path` was originally purposed to [prevent duplicate paths](https://github.com/AutomationBoi/dirjump/blob/ff74ae408a3ee0600c5cc03ff0b5117ab52ed7e2/dirjump#L164) when a  path (already in the list) is added to the top of the list. A path is really removed from the directory history when the list is full and a new path (not in the list yet) is added to the top of the list.

2019-10-11 00:36 UTC, imambungo commented on dirjump
> +	date +%s > "$last_dir_remove"
![image](https://user-images.githubusercontent.com/34421249/66616003-3cbe4f80-ebf9-11e9-9cae-d718ef5ada0f.png)

In the above image, it says a path was last removed just now, but actually nothing was removed. It just moves `~/.config` from 4 to 1.

2019-10-11 06:12 UTC, AutomationBoi commented
looking into it now

2019-10-11 06:27 UTC, AutomationBoi commented
i believe apply_max_limit_to_history is the function responsible for deletion of a path can you confirm my analysis.

2019-10-11 08:59 UTC, imambungo commented
Yes, you're right. Btw I think we can use number_of_dir_paths() like this:
```
if number_of_dir_paths > history_size
    update last_dir_remove
```

2019-10-11 13:39 UTC, AutomationBoi commented
working on the suggestion i am adding this check in the function propose_dir_path after the calling of 
insert_dir_path_to_top creating a push based on this please test

2019-10-11 14:36 UTC, imambungo commented
LGTM. Gonna merge this, thanks for the PR :+1:

2019-10-11 14:37 UTC, imambungo approved these changes

2019-10-11 14:39 UTC, merged

2019-10-12 06:56 UTC, AutomationBoi commented
:) your welcome

2019-10-22 05:00 UTC, AhmadAgus2010 commented
:+1: